export enum ViewId {
    NONE = 'NONE',
    TRANSLATION_KEY = 'TRANSLATION_KEY',
    THREE_MUSEUM = 'THREE_MUSEUM',
    THREE_MAIN = 'THREE_MAIN',
    THREE_LOBBY = 'THREE_LOBBY',


    LOBBY_REACT = 'LOBBY_REACT',
}
