export enum ViewId {
    NONE = 'NONE',
    TRANSLATION_KEY = 'TRANSLATION_KEY',
    THREE_MUSEUM = 'THREE_MUSEUM',
    THREE_MAIN = 'THREE_MAIN',
    THREE_LOBBY = 'THREE_LOBBY',
    THREE_PARK = 'THREE_PARK',
    THREE_GALERY = 'THREE_GALERY',
    GALLERIE_REACT = 'GALLERIE_REACT',
    MUSEUM_REACT = 'MUSEUM_REACT',
    LOBBY_REACT = 'LOBBY_REACT',
    GALERY_REACT = 'GALERY_REACT',
}
