export const Countries = [
  { "name": 'Global.SelectACountry', code: null, icon: 'global.svg', },
  { "name": "Africa", "dial_code": "+002", "code": "AF", "latitude": -20, "longitude": 30 },
  { "name": "Algeria", "dial_code": "+213", "code": "DZ", "latitude": 28, "longitude": 3 },
  { "name": "Andorra", "dial_code": "+376", "code": "AD", "latitude": 42.5, "longitude": 1.6 },
  { "name": "Antigua", "dial_code": "+1268", "code": "AG", "latitude": 17.05, "longitude": -61.8 },
  { "name": "Argentina", "dial_code": "+54", code: "AR", "latitude": -34, "longitude": -64, icon: 'ar.svg', },
  { "name": "Armenia", "dial_code": "+374", "code": "AM", "latitude": 40, "longitude": 45 },
  { "name": "Aruba", "dial_code": "+297", "code": "AW", "latitude": 12.5, "longitude": -69.9667 },
  { "name": "Australia", "dial_code": "+61", "code": "AU", "latitude": -27, "longitude": 133, icon: 'au.svg', },
  { "name": "Austria", "dial_code": "+43", code: "AT", "latitude": 47.3333, "longitude": 13.3333, icon: 'at.svg', },
  { "name": "Azerbaijan", "dial_code": "+994", "code": "AZ", "latitude": 40.5, "longitude": 47.5 },
  { "name": "Bahamas", "dial_code": "+1 242", "code": "BS", "latitude": 24.25, "longitude": -76 },
  { "name": "Bahrain", "dial_code": "+973",code: "BH", "latitude": 26, "longitude": 50.55, icon: 'bh.svg', },
  { "name": "Barbados", "dial_code": "+1 246", "code": "BB", "latitude": 13.1667, "longitude": -59.5333 },
  { "name": "Belarus", "dial_code": "+375", "code": "BY", "latitude": 53, "longitude": 28 },
  { "name": "Belgium", "dial_code": "+32",code: "BE", "latitude": 50.8333, "longitude": 4, icon: 'be.svg', },
  { "name": "Bermuda", "dial_code": "+1 441", "code": "BM", "latitude": 32.3333, "longitude": -64.75 },
  { "name": "Bolivia", "dial_code": "+591", "code": "BO", "latitude": -17, "longitude": -65 },
  { "name": "Bosnia", "dial_code": "+387", "code": "BA", "latitude": 44, "longitude": 18 },
  { "name": "Brazil", "dial_code": "+55",code: "BR", "latitude": -10, "longitude": -55, icon: 'br.svg', },
  { "name": "Bulgaria", "dial_code": "+359", "code": "BG", "latitude": 43, "longitude": 25 },
  { "name": "CIS", "dial_code": "+61", "code": "CX", "latitude": -10.5, "longitude": 105.6667 },
  { "name": "Canada", "dial_code": "+1",code: "CA", "latitude": 60, "longitude": -95, icon: 'ca.svg', },
  { "name": "Chile", "dial_code": "+56",code: "CL", "latitude": -30, "longitude": -71, icon: 'cl.svg', },
  { "name": "China", "dial_code": "+86",code: "CN", "latitude": 35, "longitude": 105, icon: 'cn.svg', },
  { "name": "Colombia", "dial_code": "+57", "code": "CO", "latitude": 4, "longitude": -72 },
  { "name": "Costa Rica", "dial_code": "+506", "code": "CR", "latitude": 10, "longitude": -84 },
  { "name": "Cote d'Ivoire", "dial_code": "+225", "code": "CI", "latitude": 8, "longitude": -5 },
  { "name": "Croatia", "dial_code": "+385", "code": "HR", "latitude": 45.1667, "longitude": 15.5 },
  { "name": "Curacao", "dial_code": "+53", "code": "CU", "latitude": 21.5, "longitude": -80 },
  { "name": "Cyprus", "dial_code": "+357", "code": "CY", "latitude": 35, "longitude": 33 },
  { "name": "Czech Republic", "dial_code": "+420",code: "CZ", "latitude": 49.75, "longitude": 15.5, icon: 'cz.svg', },
  { "name": "Denmark", "dial_code": "+45",code: "DK", "latitude": 56.2639, "longitude": 9.5018, icon: 'dk.svg', },
  { "name": "Dominican Republic", "dial_code": "+1 849", "code": "DO", "latitude": 19, "longitude": -70.6667 },
  { "name": "Ecuador", "dial_code": "+593", "code": "EC", "latitude": -2, "longitude": -77.5 },
  { "name": "Egypt", "dial_code": "+20", "code": "EG", "latitude": 27, "longitude": 30 },
  { "name": "El Salvador", "dial_code": "+503", "code": "SV", "latitude": 13.8333, "longitude": -88.9167 },
  { "name": "Estonia", "dial_code": "+372", "code": "EE", "latitude": 59, "longitude": 26 },
  { "name": "Finland", "dial_code": "+358", "code": "FI", "latitude": 64, "longitude": 26 },
  { "name": "France", "dial_code": "+33",code: "FR", "latitude": 46, "longitude": 2, icon: 'fr.svg', },
  { "name": "Georgia", "dial_code": "+995", "code": "GE", "latitude": 42, "longitude": 43.5 },
  { "name": "Germany", "dial_code": "+49",code: "DE", "latitude": 51, "longitude": 9, icon: 'de.svg', },
  { "name": "Ghana", "dial_code": "+233", "code": "GH", "latitude": 8, "longitude": -2 },
  { "name": "Gibraltar", "dial_code": "+350", "code": "GI", "latitude": 36.1833, "longitude": -5.3667 },
  { "name": "Greece", "dial_code": "+30",code: "GR", "latitude": 39, "longitude": 22, icon: 'gr.svg', },
  { "name": "Grenada", "dial_code": "+1 473", "code": "GD", "latitude": 12.1167, "longitude": -61.6667 },
  { "name": "Guam", "dial_code": "+1 671",code: "GU", "latitude": 13.444304, "longitude": 144.793732, icon: 'gu.svg', },
  { "name": "Guatemala", "dial_code": "+502", "code": "GT", "latitude": 15.5, "longitude": -90.25 },
  { "name": "Honduras", "dial_code": "+504", "code": "HN", "latitude": 15, "longitude": -86.5 },
  { "name": "Hong Kong", "dial_code": "+852",code: "HK", "latitude": 22.25, "longitude": 114.1667, icon: 'hk.svg', },
  { "name": "Hungary", "dial_code": "+36", "code": "HU", "latitude": 47, "longitude": 20 },
  { "name": "Iceland", "dial_code": "+354", "code": "IS", "latitude": 65, "longitude": -18 },
  { "name": "India", "dial_code": "+91",code: "IN", "latitude": 20, "longitude": 77, icon: 'in.svg', },
  { "name": "Indonesia", "dial_code": "+62",code: "ID", "latitude": 0.7893, "longitude": 113.9213, icon: 'id.svg', },
  { "name": "Ireland", "dial_code": "+353",code: "IE", "latitude": 53, "longitude": -8, icon: 'ie.svg', },
  { "name": "Israel", "dial_code": "+972", "code": "IL", "latitude": 31.5, "longitude": 34.75 },
  { "name": "Italy", "dial_code": "+39",code: "IT", "latitude": 42.8333, "longitude": 12.8333, icon: 'it.svg', },
  { "name": "Japan", "dial_code": "+81",code: "JP", "latitude": 36, "longitude": 138, icon: 'jp.svg', },
  { "name": "Jordan", "dial_code": "+962", "code": "JO", "latitude": 31, "longitude": 36 },
  { "name": "KSA", "dial_code": "+966", "code": "SA", "latitude": 25, "longitude": 45 },
  { "name": "Kazakhstan", "dial_code": "+7",code: "KZ", "latitude": 48, "longitude": 68, icon: 'kz.svg', },
  { "name": "Kenya", "dial_code": "+254", "code": "KE", "latitude": 1, "longitude": 38 },
  { "name": "Korea", "dial_code": "+850", "code": "KP", "latitude": 40, "longitude": 127 },
  { "name": "Kuwait", "dial_code": "+965",code: "KW", "latitude": 29.3375, "longitude": 47.6581, icon: 'kw.svg', },
  { "name": "Latvia", "dial_code": "+371", "code": "LV", "latitude": 57, "longitude": 25 },
  { "name": "Lebanon", "dial_code": "+961",code: "LB", "latitude": 33.8333, "longitude": 35.8333, icon: 'lb.svg', },
  { "name": "Lithuania", "dial_code": "+370", "code": "LT", "latitude": 56, "longitude": 24 },
  { "name": "Luxembourg", "dial_code": "+352",code: "LU", "latitude": 49.75, "longitude": 6.1667, icon: 'lu.svg', },
  { "name": "Macao", "dial_code": "+853",code: "MO", "latitude": 22.1667, "longitude": 113.55, icon: 'mo.svg', },
  { "name": "Malaysia", "dial_code": "+60",code: "MY", "latitude": 2.5, "longitude": 112.5, icon: 'my.svg', },
  { "name": "Maldives", "dial_code": "+960", "code": "MV", "latitude": 3.25, "longitude": 73 },
  { "name": "Malta", "dial_code": "+356", "code": "MT", "latitude": 35.8333, "longitude": 14.5833 },
  { "name": "Martinique", "dial_code": "+596", "code": "MQ", "latitude": 14.6667, "longitude": -61 },
  { "name": "Mauritius", "dial_code": "+230", "code": "MU", "latitude": -20.2833, "longitude": 57.55 },
  { "name": "Mayotte", "dial_code": "+262", "code": "YT", "latitude": -12.8333, "longitude": 45.1667 },
  { "name": "Mexico", "dial_code": "+52",code: "MX", "latitude": 23, "longitude": -102, icon: 'mx.svg', },
  { "name": "Moldova", "dial_code": "+373", "code": "MD", "latitude": 47, "longitude": 29 },
  { "name": "Monaco", "dial_code": "+377",code: "MC", "latitude": 43.7384, "longitude": 7.4246, icon: 'mc.svg', },
  { "name": "Morocco", "dial_code": "+212", "code": "MA", "latitude": 32, "longitude": -5 },
  { "name": "Netherlands", "dial_code": "+31",code: "NL", "latitude": 52.5, "longitude": 5.75, icon: 'nl.svg', },
  { "name": "New Zealand", "dial_code": "+64", "code": "NZ", "latitude": -41, "longitude": 174 },
  { "name": "Nicaragua", "dial_code": "+505", "code": "NI", "latitude": 13, "longitude": -85 },
  { "name": "Norway", "dial_code": "+47",code: "NO", "latitude": 62, "longitude": 10, icon: 'no.svg', },
  { "name": "Oman", "dial_code": "+968", "code": "OM", "latitude": 21, "longitude": 57 },
  { "name": "Panama", "dial_code": "+507",code: "PA", "latitude": 9, "longitude": -80, icon: 'pa.svg', },
  { "name": "Paraguay", "dial_code": "+595", "code": "PY", "latitude": -23, "longitude": -58 },
  { "name": "Peru", "dial_code": "+51", "code": "PE", "latitude": -10, "longitude": -76 },
  { "name": "Philippines", "dial_code": "+63",code: "PH", "latitude": 12.8797, "longitude": 121.774, icon: 'ph.svg', },
  { "name": "Poland", "dial_code": "+48",code: "PL", "latitude": 52, "longitude": 20, icon: 'pl.svg', },
  { "name": "Portugal", "dial_code": "+351",code: "PT", "latitude": 39.5, "longitude": -8, icon: 'pt.svg', },
  { "name": "Puerto Rico", "dial_code": "+1 939", "code": "PR", "latitude": 18.25, "longitude": -66.5 },
  { "name": "Qatar", "dial_code": "+974",code: "QA", "latitude": 25.5, "longitude": 51.25, icon: 'qa.svg', },
  { "name": "Romania", "dial_code": "+40", "code": "RO", "latitude": 46, "longitude": 25 },
  { "name": "Russia", "dial_code": "+7",code: "RU", "latitude": 60, "longitude": 100, icon: 'ru.svg', },
  { "name": "Réunion", "dial_code": "+262", "code": "RE", "latitude": -21.1, "longitude": 55.6 },
  { "name": "Senegal", "dial_code": "+221", "code": "SN", "latitude": 14, "longitude": -14 },
  { "name": "Serbia", "dial_code": "+381", "code": "RS", "latitude": 44, "longitude": 21 },
  { "name": "Singapore", "dial_code": "+65",code: "SG", "latitude": 1.3667, "longitude": 103.8, icon: 'sg.svg', },
  { "name": "Slovakia", "dial_code": "+421", "code": "SK", "latitude": 48.6667, "longitude": 19.5 },
  { "name": "Slovenia", "dial_code": "+386", "code": "SI", "latitude": 46, "longitude": 15 },
  { "name": "South Africa", "dial_code": "+27", "code": "ZA", "latitude": -29, "longitude": 24 },
  { "name": "South Korea", "dial_code": "+82",code: "KR", "latitude": 37.5326, "longitude": 127.024612, icon: 'kr.svg', },
  { "name": "Spain", "dial_code": "+34",code: "ES", "latitude": 40, "longitude": -4, icon: 'es.svg', },
  { "name": "Sweden", "dial_code": "+46",code: "SE", "latitude": 62, "longitude": 15, icon: 'se.svg', },
  { "name": "Switzerland", "dial_code": "+41",code: "CH", "latitude": 47, "longitude": 8 , icon: 'ch.svg',},
  { "name": "Taiwan", "dial_code": "+886",code: "TW", "latitude": 23.5, "longitude": 121, icon: 'tw.svg', },
  { "name": "Thailand", "dial_code": "+66",code: "TH", "latitude": 15, "longitude": 100, icon: 'th.svg', },
  { "name": "Tunisia", "dial_code": "+216", "code": "TN", "latitude": 34, "longitude": 9 },
  { "name": "Türkiye", "dial_code": "+90",code: "TR", "latitude": 39, "longitude": 35, icon: 'tr.svg', },
  { "name": "Ukraine", "dial_code": "+380", "code": "UA", "latitude": 49, "longitude": 32 },
  { "name": "United Arab Emirates", "dial_code": "+971",code: "AE", "latitude": 24, "longitude": 54, icon: 'ae.svg', },
  { "name": "United Kingdom", "dial_code": "+44",code: "GB", "latitude": 54, "longitude": -2, icon: 'gb.svg', },
  { "name": "United States", "dial_code": "+1",code: "US", "latitude": 38, "longitude": -97, icon: 'us.svg', },
  { "name": "Uruguay", "dial_code": "+598", "code": "UY", "latitude": -33, "longitude": -56 },
  { "name": "Uzbekistan", "dial_code": "+998", "code": "UZ", "latitude": 41, "longitude": 64 },
  { "name": "Venezuela", "dial_code": "+58", "code": "VE", "latitude": 8, "longitude": -66 },
  { "name": "Viet Nam", "dial_code": "+84",code: "VN", "latitude": 16, "longitude": 106, icon: 'vn.svg', },
  { "name": "_others", "dial_code": "+001", "code": "OT", "latitude": -15, "longitude": 30 },
]
