export enum AssetId {
    NONE = 'NONE',

    GLTF_LOBBY = 'GLTF_LOBBY',
    GLTF_MUSEUM = 'GLTF_MUSEUM',
    GLTF_COMMON = 'GLTF_COMMON',

    HDR_LOBBY = 'HDR_LOBBY',
    HDR_LOBBY_2 = 'HDR_LOBBY_2',
    HDR_MUSEUM = 'HDR_MUSEUM',
    HDR_AUTOMN = 'HDR_AUTOMN',
    HDR_WINTER = 'HDR_WINTER',

    TEXTURE_LUT_GLOBAL = 'TEXTURE_LUT_GLOBAL',
    TEXTURE_MIDDLE_BLOC = 'TEXTURE_MIDDLE_BLOC',
    TEXTURE_WALL_BAKE = 'TEXTURE_WALL_BAKE',
    TEXTURE_FLOAR = 'TEXTURE_FLOAR',
    TEXTURE_WALL = 'TEXTURE_WALL',

    TEXTURE_GROUND = 'TEXTURE_GROUND',
    TEXTURE_WALL_MUSEUM = 'TEXTURE_WALL_MUSEUM',
}