export enum AssetId {
    NONE = 'NONE',


    // 3D models
    GLTF_LOBBY = 'GLTF_LOBBY',
    HDR_LOBBY = 'HDR_LOBBY',
    HDR_AUTOMN = 'HDR_AUTOMN',
    HDR_WINTER = 'HDR_WINTER',
    GLTF_COMMON = 'GLTF_COMMON',

    TEXTURE_SKY = 'TEXTURE_SKY',
    TEXTURE_SKY_CLOUDS = 'TEXTURE_SKY_CLOUDS',
    TEXTURE_WHITE = 'TEXTURE_WHITE',

    TEXTURE_LUT_GLOBAL = 'TEXTURE_LUT_GLOBAL',


}