export enum AssetId {
    NONE = 'NONE',


    // 3D models
    GLTF_LOBBY = 'GLTF_LOBBY',
    GLTF_MUSEUM = 'GLTF_MUSEUM',
    GLTF_PARK = 'GLTF_PARK',

    HDR_LOBBY = 'HDR_LOBBY',
    HDR_MUSEUM = 'HDR_MUSEUM',
    HDR_PARK = 'HDR_PARK',
    HDR_AUTOMN = 'HDR_AUTOMN',
    HDR_WINTER = 'HDR_WINTER',
    GLTF_COMMON = 'GLTF_COMMON',

    TEXTURE_SKY = 'TEXTURE_SKY',
    TEXTURE_SKY_CLOUDS = 'TEXTURE_SKY_CLOUDS',
    TEXTURE_WHITE = 'TEXTURE_WHITE',

    TEXTURE_LUT_GLOBAL = 'TEXTURE_LUT_GLOBAL',
    TEXTURE_MIDDLE_BLOC = 'TEXTURE_MIDDLE_BLOC',
    TEXTURE_WALL_BAKE = 'TEXTURE_WALL_BAKE',
    TEXTURE_FLOAR = 'TEXTURE_FLOAR',
    TEXTURE_WALL = 'TEXTURE_WALL',
    TEXTURE_AQUARELLE = 'TEXTURE_AQUARELLE',

    TEXTURE_GROUND = 'TEXTURE_GROUND',
    TEXTURE_WALL_MUSEUM = 'TEXTURE_WALL_MUSEUM',
    TEXTURE_TITLE = 'TEXTURE_TITLE',
    TEXTURE_CLOUDS = 'TEXTURE_CLOUDS',
    TEXTURE_LEFT_WALL = 'TEXTURE_LEFT_WALL',
}